### ISSUE TITLE
Background tabs text not quite visible

### ISSUE THREAD

**Issue by hnavia** [dracula/google-chrome#22]
I've installed the theme and it looks great but the only problem I've seen is that the text in the tabs not being used are a bit dark and, some times, it's hard to read them.

Any chance the text can be a bit brighter or even white?

Thanks in advance.

![image](https://user-images.githubusercontent.com/69368602/173374636-de839f1e-dcd7-4fd2-83a9-7fbd98ee5723.png)

**Comment by nickimola** [comment]
Hi
I wouldn't really set them to white as then it will make them easily mistaken for the active tab.
I just released a small update that makes the background color slightly dark. Let me know if you think it's better this way and if it is easier to read.

**Comment by hnavia** [comment]
It does work better but the text on good light condition is still not to easy to read.

Any chance to not make it white but maybe slightly clearer? Maybe something like this? #D6ACFF or maybe even the same color as of top color of the selected tab which is much more bright.

I know it also will depend a lot on the monitor and light conditions I work but make the text a bit lighter in color should do the trick.

Thank you very much in advance for your help!

**Comment by nickimola** [comment]
The problem here is that It is a bit hard to find the right balance for everybody
If i change that color, a lot of people will say that the chosen color is not in the color list for the original theme and they will complain.
I have created a manifest file just for you so that you can have it modified as per your request. Inside the xip file you have a manifest file (the theme) and a readme on how to install it on your version of chrome

[google-chrome-custom 2.zip](https://github.com/dracula/google-chrome/files/8897571/google-chrome-custom.2.zip)

Hope this is good enough for you :)

**Comment by hnavia** [comment]
Well I was saying to stick with the colors but use the one at the top of the selected tab as for the characters colors.

Thank you very much for your help. I really like this theme but not being able to properly read the background tabs was a bit complicated for me.

I was checking the color palette and I agree with you actually, the chosen color is the best one mostly because the one I want to use, although it makes the color brighter and more readable to me, it definitely looks to bright and it kind of makes me loose focus. I will play around a bit as Dracula color palette seems to be a little bit limited for this purpose.

Thank you very much for your help! I really appreciate it.

**Comment by nickimola** [comment]
Glad to help!
Feel free to re-open the ticket if you think something more comes up.
Closing it for now
